var map = {
    "action": 17,
    "backend": 22,
    "basketball": 2,
    "blues": 11,
    "classical music": 10,
    "devops": 24,
    "drama": 18,
    "electronic": 13,
    "fantasy": 19,
    "football": 1,
    "frontend": 21,
    "fullstack": 23,
    "golang": 29,
    "graffiti": 16,
    "hiking": 14,
    "hip-hop": 9,
    "hockey": 3,
    "java": 27,
    "jazz": 12,
    "js": 26,
    "php": 28,
    "pop": 8,
    "python": 25,
    "rock": 7,
    "sci-fi": 20,
    "skateboard": 6,
    "ski": 4,
    "snowboard": 5,
    "street walking": 15
};